#!/bin/bash

DEST_VOL="${1}"
EFI_ROOT_DIR="${2:-${DEST_VOL%*/}/EFIROOTDIR}"
partutil="./partutil"
exitcode=1

DiskDevice=$(LC_ALL=C diskutil info "${DEST_VOL}" 2>/dev/null | \
                              sed -n 's/.*Part [oO]f Whole: *//p')

if [[ -z "$DiskDevice" ]]; then
    echo "Can't find volume with the name ${DEST_VOL}"
    exit $exitcode
fi

# echo "DiskDevice = $DiskDevice"

ESPDevice=$("$partutil" --find-esp "$DiskDevice")

# we have an ESP?
if [[ -n "$ESPDevice" ]]; then
  # Get the ESP mount point if the partition is currently mounted
  ESPMountPoint=$("$partutil" --show-mountpoint "$ESPDevice")
  if [[ -n "$ESPMountPoint" ]]; then
    # If already mounted it's okay
    exitcode=0
  else
    # Else try to mount the ESP partition
    ESPMountPoint="/Volumes/ESP"
    exitcode=1
    fstype=$($partutil --show-fstype $ESPDevice)
    if [[ -n "$fstype" ]]; then
      [[ ! -d "${ESPMountPoint}" ]] && mkdir -p "${ESPMountPoint}"
      mount -t $fstype /dev/$ESPDevice "${ESPMountPoint}" 2>&1
      exitcode=$?
    fi
  fi

  # if I'm here is because I'v selected to install on the ESP: go to fail if the ESP failed to mount
  if [[ $exitcode -ne 0 ]]; then
    echo
    echo "ERROR: can't mount ESP partition ($ESPDevice) !"
    echo "Check that the partition is well formated in HFS or Fat32."
    echo
    echo "To format as HFS use command like:"
    echo "sudo newfs_hfs -v EFI /dev/r$ESPDevice"
    echo
    echo "For format as Fat32 use command like:"
    echo "sudo newfs_msdos -v EFI -F 32 /dev/r$ESPDevice"
  else
    ln -sf "$ESPMountPoint" "$EFI_ROOT_DIR"
  fi
else
  # Disk is not GPT, or not contanis an ESP, use the DEST_VOL as EFI_ROOT_DIR
  ln -sf "${DEST_VOL}" "$EFI_ROOT_DIR"
  exitcode=0
fi

exit $exitcode
